### ISSUE TITLE
Problem importing ARUnity6-6.0.2.unitypackage in Unity 5.6

### ISSUE THREAD

**Issue by ljimenez29** [artoolkit/ar6unity-wiki#4]
Hello everyone.

I have not been able to make Artoolkit6 work on Unity. When I import the ARUnity6-6.0.2.unitypackage file the window shown in the image is displayed. 

![error](https://user-images.githubusercontent.com/27974413/28679296-bf0f2ab8-72c0-11e7-9394-d945b662bb42.png)

Once I press any of the buttons on the window, Unity closes and I do not care about the package.

I'm using Windows 10 and Unity 5.6. I do not know how to solve this problem.

Sorry for my English

Thank you

**Comment by ThorstenBux** [comment]
Hi, sorry Windows support is not implemented at the moment.
