### ISSUE TITLE
Unable to download ARUnity6.unitypackage 

### ISSUE THREAD

**Issue by noder123** [artoolkit/ar6unity-wiki#5]
When downloading from http://artoolkit-dist.s3.amazonaws.com/arunity6/6.0/ARUnity6.unitypackage I'm getting the "AccessDeniedAccess Denied3C42845274760EF6dMqa7kcklwodB0L6hadZbF3xgv2n/ZE4GAyudRoKOFKN3UwyfsWDdu4hCqaOiKWOLaa3aCWR16Y=" error. Can you please update the Wiki with the latest download link?

Thanks!

**Comment by ThorstenBux** [comment]
Just use the download page here:
http://artoolkit.org/download.html

**Comment by IARI** [comment]
I couldn't find any working link.
neither http://artoolkit-dist.s3.amazonaws.com/arunity6/6.0/ARUnity6.unitypackage which is referenced in the wiki nor https://archive.artoolkit.org/download.html work for me.
